spring:
  config:
    import: optional:classpath:.env[.properties]

  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  web:
    error:
      include-stacktrace: never
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useTimeZone=true&serverTimezone=UTC&createDataBaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


server:
  servlet:
    context-path: /
  port: 8090


