spring:
  application:
    name: anime-service
  web:
    error:
      include-stacktrace: on_param
  threads:
    virtual:
      enabled: true
  mvc:
    apiversion:
      use:
        header: X-API-Version
      default: 1
server:
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20

logging:
  level:
    io.github.danielcampossantos: DEBUG

database:
  url: "${DB_URL:localhost}:${DB_PORT:3306}"
  username: "${LOCAL_USERNAME:daniel}"
  password: "${LOCAL_PASSWORD:123456}"

