spring:
  config:
    import: optional:classpath:.env[.properties]
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/anime-service?useTimeZone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER}
    password: ${ENV_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20

management:
  server:
    port: 8989
  endpoints:
    web:
      exposure:
        include: "*"

